# VISUALIZE DEVELOPED COUNTRIES AND INDIA

Import the libraries

In [2]:
%matplotlib inline  
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
#import seaborn as sns

Import the dataset from the file system

In [3]:
#India_dataset = 'Dataset/India_Data/API_IND_DS2_en_csv_v2_10135894/API_IND_DS2_en_csv_v2_10135894.csv'
GDP_dataset = 'Dataset/GDP/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_10134290/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_10134290.csv'
HDI_dataset = 'Dataset/HDI/Human Development Index (HDI).csv'
Infant_Mortality_dataset = 'Dataset/Infant_Mortality_Rate/API_SP.DYN.IMRT.IN_DS2_en_csv_v2_10181276/API_SP.DYN.IMRT.IN_DS2_en_csv_v2_10181276.csv'
Life_Expectancy_dataset = 'Dataset/Life_Expectancy/API_SP.DYN.LE00.IN_DS2_en_csv_v2_10181296/API_SP.DYN.LE00.IN_DS2_en_csv_v2_10181296.csv'

Define a function which returns a list of 33 developed countries as per per CIA (https://www.cia.gov/library/publications/the-world-factbook/appendix/appendix-b.html#D)

NOTE: 
1. Taiwan data doesnt exist in the world bank database. So, ommitted.
2. Hong Kong data doesnt exist in the world bank database for Infant Mortality Rate. So, ommitted.

In [4]:
def developed_countries_list():
    dc_list = []
    dc_list.append("Australia")
    dc_list.append("Austria")
    dc_list.append("Belgium")
    dc_list.append("Canada")
    dc_list.append("Cyprus")
    dc_list.append("Czech Republic")
    dc_list.append("Denmark")
    dc_list.append("Finland")
    dc_list.append("France")
    dc_list.append("Germany")
    dc_list.append("Greece")
    #dc_list.append("Hong Kong SAR, China")
    dc_list.append("Iceland")
    dc_list.append("Ireland")
    dc_list.append("Israel")
    dc_list.append("Italy")
    dc_list.append("Japan")
    dc_list.append("Korea, Rep.")
    dc_list.append("Luxembourg")
    dc_list.append("Malta")
    dc_list.append("Netherlands")
    dc_list.append("New Zealand")
    dc_list.append("Norway")
    dc_list.append("Portugal")
    dc_list.append("Singapore")
    dc_list.append("Slovak Republic")
    dc_list.append("Slovenia")
    dc_list.append("Spain")
    dc_list.append("Sweden")
    dc_list.append("Switzerland")
    #dc_list.append("Taiwan")
    dc_list.append("United Kingdom")
    dc_list.append("United States")
    return dc_list

Get the dataframes from the csv files

In [5]:
gdp_df = pd.read_csv(GDP_dataset,skiprows=3)
hdi_df = pd.read_csv(HDI_dataset,skiprows=1)
im_df = pd.read_csv(Infant_Mortality_dataset,skiprows=3)
le_df = pd.read_csv(Life_Expectancy_dataset,skiprows=3)

For the **hdi_df** dataframe:
1. Filter NAN columns which are alternate
2. Remove the space from the name of the countries in the Country column
3. Rename the countries which have different name in the other dataframes to make data same throughout
4. Add INDIA to the list of countries so as to make an analysis with other countries.

In [7]:
# Filter NAN columns which are alternate
hdi_drop_col = []
for i in range(3,hdi_df.shape[1]):
    if(i%2 == 1):
        hdi_drop_col.append(i)
hdi_df = hdi_df.drop(hdi_df.columns[hdi_drop_col], axis=1)

# Remove initial spaces from the countries names 
# AND
# Rename country names list and make it similar to the World Bank dataset
for i in range(0,hdi_df['Country'].shape[0]):
    s = hdi_df['Country'][i]
    if(s[1:] == "Czechia"):
        hdi_df['Country'][i] = "Czech Republic"
    #elif(s == "Hong Kong, China (SAR)"):
    #    s = "Hong Kong SAR, China"
    elif(s[1:] == "Korea (Republic of)"):
        hdi_df['Country'][i] = "Korea, Rep."
    elif(s[1:] == "Slovakia"):
        hdi_df['Country'][i] = "Slovak Republic"
    else:
        hdi_df['Country'][i] = s[1:]

# Get the list of all developed countries   
countries_list = developed_countries_list()
# Add India among other countries for comparison and analysis
countries_list.append("India")

/Users/siddhant/miniconda/envs/dataScience_env/lib/python2.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Filter all the dataframes with the countries that are in the list : countries_list

In [9]:
developed_gdp_df = gdp_df[gdp_df['Country Name'].isin(countries_list)]
developed_im_df = im_df[im_df['Country Name'].isin(countries_list)]
developed_le_df = le_df[le_df['Country Name'].isin(countries_list)]
developed_hdi_df = hdi_df[hdi_df['Country'].isin(countries_list)]

KeyError: 'Country Name'

Filter GDP data from 1995 - 2016 <br/>
Normalize the GDP data row wise

In [ ]:
#Filter
developed_gdp_df_filtered = developed_gdp_df.drop(developed_gdp_df.columns[1:39], axis=1)
developed_gdp_final_df = developed_gdp_df_filtered.drop(developed_gdp_df_filtered.columns[[developed_gdp_df_filtered.shape[1]-2,developed_gdp_df_filtered.shape[1]-1]], axis=1)
developed_gdp_final_df = developed_gdp_final_df.reset_index(drop=True)

#Normalize
developed_gdp_final_rowmax = developed_gdp_final_df.select_dtypes(include='float64').max(axis=1)
for i in range(0,developed_gdp_final_df.shape[0]):
    rowmax = developed_gdp_final_rowmax[i]
    for j in range(0,developed_gdp_final_df.columns[1:].shape[0]):
        data = developed_gdp_final_df.loc[i, developed_gdp_final_df.columns[1:][j]]
        data = data/rowmax
        developed_gdp_final_df.loc[i, developed_gdp_final_df.columns[1:][j]] = data

Filter Infant Mortality Rate data from 1995 - 2016 <br/>
Normalize the Infant Mortality Rate data row wise

In [ ]:
#Filter
developed_im_df_filtered = developed_im_df.drop(developed_im_df.columns[1:39], axis=1)
developed_im_final_df = developed_im_df_filtered.drop(developed_im_df_filtered.columns[[developed_im_df_filtered.shape[1]-2,developed_im_df_filtered.shape[1]-1]], axis=1)
developed_im_final_df = developed_im_final_df.reset_index(drop=True)

#Normalize
developed_im_final_rowmax = developed_im_final_df.select_dtypes(include='float64').max(axis=1)
for i in range(0,developed_im_final_df.shape[0]):
    rowmax = developed_im_final_rowmax[i]
    for j in range(0,developed_im_final_df.columns[1:].shape[0]):
        data = developed_im_final_df.loc[i, developed_im_final_df.columns[1:][j]]
        data = data/rowmax
        developed_im_final_df.loc[i, developed_im_final_df.columns[1:][j]] = data

Filter Life Expectancy data from 1995 - 2016 <br/>
Normalize the Life Expectancy data row wise

In [9]:
#Filter
developed_le_df_filtered = developed_le_df.drop(developed_le_df.columns[1:39], axis=1)
developed_le_final_df = developed_le_df_filtered.drop(developed_le_df_filtered.columns[[developed_le_df_filtered.shape[1]-2,developed_le_df_filtered.shape[1]-1]], axis=1)
developed_le_final_df = developed_le_final_df.reset_index(drop=True)

#Normalize
developed_le_final_rowmax = developed_le_final_df.select_dtypes(include='float64').max(axis=1)
for i in range(0,developed_le_final_df.shape[0]):
    rowmax = developed_le_final_rowmax[i]
    for j in range(0,developed_le_final_df.columns[1:].shape[0]):
        data = developed_le_final_df.loc[i, developed_le_final_df.columns[1:][j]]
        data = data/rowmax
        developed_le_final_df.loc[i, developed_le_final_df.columns[1:][j]] = data

Filter Human Development Index data from 1995 - 2016 <br/>
Normalize the Human Development Index data row wise is already done in the dataset

In [10]:
#Filter
developed_hdi_df_filtered = developed_hdi_df.drop(developed_hdi_df.columns[2:7], axis=1)
developed_hdi_df_filtered = developed_hdi_df.drop(developed_hdi_df.columns[[developed_hdi_df.shape[1]-1]], axis=1)
developed_hdi_final_df = developed_hdi_df_filtered.drop(developed_hdi_df_filtered.columns[0], axis=1)
developed_hdi_final_df = developed_hdi_final_df.reset_index(drop=True)

Sort all the Dataframes

In [11]:
developed_gdp_sorted_df = developed_gdp_final_df.sort_values(by=['Country Name'])
developed_im_sorted_df = developed_im_final_df.sort_values(by=['Country Name'])
developed_le_sorted_df = developed_le_final_df.sort_values(by=['Country Name'])
developed_hdi_sorted_df = developed_hdi_final_df.sort_values(by=['Country'])

In [12]:
developed_hdi_sorted_df

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Australia,0.866,0.867,0.868,0.872,0.875,0.883,0.886,0.889,0.892,...,0.915,0.920,0.921,0.923,0.925,0.929,0.931,0.933,0.936,0.938
1,Austria,0.795,0.800,0.805,0.807,0.813,0.817,0.820,0.824,0.835,...,0.881,0.884,0.886,0.895,0.897,0.899,0.897,0.901,0.903,0.906
2,Belgium,0.806,0.810,0.825,0.839,0.845,0.852,0.857,0.862,0.866,...,0.899,0.899,0.899,0.903,0.904,0.905,0.908,0.909,0.913,0.915
3,Canada,0.849,0.853,0.856,0.854,0.859,0.861,0.863,0.862,0.861,...,0.897,0.899,0.899,0.902,0.905,0.908,0.911,0.918,0.920,0.922
4,Cyprus,0.732,0.735,0.740,0.777,0.781,0.786,0.789,0.792,0.800,...,0.846,0.852,0.856,0.850,0.853,0.852,0.853,0.856,0.860,0.867
5,Czech Republic,0.730,0.726,0.728,0.735,0.744,0.753,0.768,0.774,0.775,...,0.850,0.854,0.857,0.862,0.865,0.865,0.874,0.879,0.882,0.885
6,Denmark,0.799,0.804,0.809,0.815,0.824,0.831,0.837,0.843,0.849,...,0.904,0.909,0.906,0.910,0.922,0.924,0.931,0.928,0.926,0.928
7,Finland,0.784,0.787,0.795,0.799,0.809,0.816,0.823,0.832,0.840,...,0.901,0.904,0.899,0.903,0.907,0.908,0.912,0.914,0.915,0.918
8,France,0.779,0.788,0.798,0.804,0.818,0.825,0.830,0.834,0.839,...,0.876,0.878,0.878,0.882,0.884,0.886,0.889,0.894,0.898,0.899
9,Germany,0.801,0.809,0.814,0.824,0.829,0.834,0.839,0.844,0.850,...,0.915,0.917,0.917,0.921,0.926,0.928,0.928,0.930,0.933,0.934
10,Greece,0.753,0.763,0.764,0.762,0.766,0.768,0.772,0.777,0.787,...,0.849,0.857,0.858,0.856,0.852,0.854,0.856,0.864,0.866,0.868
11,Iceland,0.802,0.815,0.818,0.818,0.823,0.826,0.831,0.840,0.849,...,0.897,0.890,0.890,0.891,0.901,0.909,0.920,0.925,0.927,0.933
12,India,0.427,0.432,0.438,0.445,0.452,0.460,0.467,0.473,0.480,...,0.556,0.564,0.570,0.581,0.591,0.600,0.607,0.618,0.627,0.636
13,Ireland,0.763,0.767,0.773,0.781,0.789,0.795,0.801,0.809,0.840,...,0.908,0.908,0.906,0.909,0.895,0.902,0.911,0.921,0.929,0.934
14,Israel,0.792,0.800,0.807,0.812,0.818,0.823,0.828,0.835,0.843,...,0.881,0.880,0.882,0.887,0.892,0.893,0.895,0.899,0.901,0.902
15,Italy,0.769,0.774,0.780,0.786,0.794,0.800,0.806,0.814,0.819,...,0.866,0.868,0.868,0.870,0.875,0.874,0.876,0.874,0.876,0.878
16,Japan,0.816,0.821,0.824,0.829,0.835,0.840,0.845,0.848,0.847,...,0.880,0.881,0.880,0.885,0.890,0.895,0.899,0.903,0.905,0.907
17,"Korea, Rep.",0.728,0.739,0.746,0.756,0.767,0.778,0.789,0.800,0.797,...,0.869,0.874,0.869,0.884,0.888,0.890,0.893,0.896,0.898,0.900
18,Luxembourg,0.782,0.790,0.795,0.799,0.803,0.808,0.817,0.826,0.834,...,0.888,0.890,0.883,0.889,0.892,0.892,0.892,0.895,0.899,0.904
19,Malta,0.740,0.745,0.749,0.753,0.756,0.759,0.763,0.768,0.776,...,0.827,0.829,0.830,0.843,0.843,0.849,0.856,0.862,0.871,0.875
20,Netherlands,0.829,0.834,0.835,0.839,0.864,0.861,0.866,0.865,0.867,...,0.904,0.906,0.906,0.910,0.921,0.921,0.923,0.924,0.926,0.928
21,New Zealand,0.818,0.820,0.825,0.836,0.845,0.851,0.854,0.860,0.863,...,0.894,0.894,0.898,0.899,0.902,0.905,0.907,0.910,0.914,0.915
22,Norway,0.850,0.856,0.862,0.870,0.885,0.883,0.888,0.894,0.906,...,0.938,0.938,0.938,0.942,0.943,0.942,0.946,0.946,0.948,0.951
23,Portugal,0.711,0.720,0.732,0.745,0.753,0.760,0.767,0.773,0.780,...,0.810,0.814,0.817,0.822,0.826,0.829,0.837,0.839,0.842,0.845
24,Singapore,0.718,0.729,0.740,0.751,0.763,0.773,0.782,0.793,0.798,...,0.878,0.883,0.884,0.909,0.914,0.920,0.923,0.928,0.929,0.930
25,Slovak Republic,0.739,0.734,0.733,0.737,0.743,0.751,0.754,0.757,0.763,...,0.814,0.822,0.824,0.829,0.837,0.842,0.844,0.845,0.851,0.853
26,Slovenia,0.767,0.765,0.766,0.769,0.775,0.782,0.788,0.796,0.805,...,0.873,0.878,0.878,0.882,0.884,0.877,0.885,0.887,0.889,0.894
27,Spain,0.754,0.764,0.772,0.782,0.791,0.800,0.806,0.810,0.814,...,0.853,0.856,0.858,0.865,0.870,0.873,0.875,0.880,0.885,0.889
28,Sweden,0.816,0.818,0.821,0.840,0.849,0.856,0.863,0.874,0.888,...,0.905,0.901,0.899,0.905,0.906,0.908,0.912,0.920,0.929,0.932
29,Switzerland,0.832,0.834,0.836,0.841,0.844,0.848,0.854,0.864,0.873,...,0.915,0.917,0.927,0.932,0.932,0.935,0.938,0.939,0.942,0.943
30,United Kingdom,0.775,0.788,0.801,0.814,0.827,0.839,0.844,0.849,0.855,...,0.892,0.896,0.899,0.905,0.899,0.898,0.915,0.919,0.918,0.920
31,United States,0.860,0.861,0.867,0.871,0.875,0.877,0.879,0.881,0.884,...,0.905,0.910,0.910,0.914,0.917,0.918,0.916,0.918,0.920,0.922

In [2]:
final_df = pd.DataFrame().reindex_like(developed_gdp_sorted_df)
for i in range(0,developed_gdp_sorted_df.shape[0]):
    final_df.loc[i, final_df.columns[0]] = developed_gdp_sorted_df.loc[i,developed_gdp_sorted_df.columns[0]]
    for j in range(0,developed_gdp_sorted_df.columns[1:].shape[0]):
        data = (developed_gdp_sorted_df.loc[i, developed_gdp_sorted_df.columns[1:][j]] + developed_im_sorted_df.loc[i, developed_im_sorted_df.columns[1:][j]] + developed_le_sorted_df.loc[i, developed_le_sorted_df.columns[1:][j]] + developed_hdi_sorted_df.loc[i, developed_hdi_sorted_df.columns[1:][j]])/4
        final_df.loc[i, final_df.columns[1:][j]] = data

NameError: name 'pd' is not defined

In [1]:
final_df

NameError: name 'final_df' is not defined